# Generated by Django 3.1.7 on 2021-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210521_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.TextField(),
        ),
    ]
