# Generated by Django 3.1.7 on 2021-05-20 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('netflix', models.TextField(default='')),
                ('watcha', models.TextField(default='')),
                ('wavve', models.TextField(default='')),
                ('naver', models.TextField(default='')),
                ('release_date', models.DateField()),
                ('clicked', models.IntegerField(default=0)),
                ('last_cliked_time', models.DateTimeField(default=datetime.datetime(2021, 5, 18, 7, 30, 30, tzinfo=utc))),
            ],
        ),
    ]
