# Generated by Django 3.1.7 on 2021-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_nowshowingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovie',
            name='userRating',
            field=models.IntegerField(default=0),
        ),
    ]
