# Generated by Django 3.1.7 on 2021-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_vote_votecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option_two_count',
        ),
        migrations.AddField(
            model_name='vote',
            name='option_one',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='option_two',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
