# Generated by Django 3.1.7 on 2021-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_nowshowingmovie_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='userRating',
            field=models.FloatField(default=0),
        ),
    ]
